Repository emissary-ingress/emissary, pull requests merged in 2022-09, with the labels that each got.

#4503 v2.x Python dep updates
  DEPENDENCIES.md
  Makefile
  python/requirements.txt
  tools/src/py-mkopensource/main.go
Labels: dependencies

#4318 Fix label selector to match standard kubernetes behaviour
  CHANGELOG.md
  python/ambassador/ir/irutils.py
Labels: t:debt, t:bug

#4499 Fix label selector matching and host/mapping pairing
  python/ambassador/ir/irhost.py
  python/ambassador/ir/irutils.py
Labels: t:debt, t:bug

#4529 diagnostics: properly parse metrics with colons in name
  CHANGELOG.md
  docs/releaseNotes.yml
  python/ambassador/diagnostics/envoy_stats.py
Labels: t:bug, v3.2, v2.5

#4544 deps : adding python + docker to dependabot
  .github/dependabot.yml
Labels: dependencies
