Repository emissary-ingress/emissary, pull requests merged in 2024-08, with the labels that each got.

#5735 Fix Lint
  python/ambassador/fetch/dependency.py
Labels: python, size:XS, lgtm

#5733 Re-adding HostIP to helm charts and deployments
  charts/emissary-ingress/templates/deployment.yaml
  manifests/emissary/emissary-defaultns.yaml.in
  manifests/emissary/emissary-emissaryns.yaml.in
  python/tests/integration/manifests/ambassador.yaml
Labels: friction, size:S, lgtm

#5731 Add Helm Chart Support for Opt-In Support for Exposing Port 8878 in the AdminService
  charts/emissary-ingress/templates/admin-service.yaml
  charts/emissary-ingress/templates/deployment.yaml
  charts/emissary-ingress/values.yaml.in
Labels: t:feature, size:S, lgtm

#5761 dev(chainsaw): refactor ci
  .circleci/config.yml
  .dockerignore
  .github/actions/after-job/action.yml
  .github/actions/collect-logs/action.yml
  .github/actions/git-dirty-check/action.yml
  .github/actions/setup-deps/action.yml
  .github/dependabot.yml
  .github/stale.yml
  .github/workflows/ci.yaml
  .github/workflows/deprecated/check-branch-version.yml
  .github/workflows/deprecated/execute-tests-and-promote.yml
  .github/workflows/deprecated/k8s-e2e.yml
  .github/workflows/deprecated/promote-ga.yml
  .github/workflows/deprecated/promote-rc.yml
  .github/workflows/deprecated/publish-chart.yml
  .gitignore
  .goreleaser.yaml
  Makefile
  build-aux/builder.mk
  build-aux/deps.mk
  go.mod
  pyproject.toml
Labels: deprecation, github_actions, size:XL, lgtm

#5763 Activate CI for dev/v4
  .github/workflows/ci.yaml
  build-aux/builder.mk
  build-aux/main.mk
  python/ambassador/config/acmapping.py
  python/ambassador/config/acpragma.py
  python/ambassador/config/acresource.py
  python/ambassador/fetch/fetcher.py
  python/ambassador/ir/irbuffer.py
  python/ambassador/ir/irfilter.py
  python/ambassador/ir/irgzip.py
  python/ambassador/ir/irresource.py
  python/ambassador/ir/irretrypolicy.py
  python/ambassador/ir/irtls.py
  python/ambassador/ir/irtracing.py
  python/ambassador/resource.py
  python/ambassador/scout.py
  python/tests/kat/t_hosts.py
  python/tests/unit/test_lookup.py
Labels: python, github_actions, size:L, lgtm

#5758 Sync dev/v4
  .goreleaser.yaml
  charts/emissary-ingress/templates/deployment.yaml
  manifests/emissary/emissary-defaultns.yaml.in
  manifests/emissary/emissary-emissaryns.yaml.in
  python/tests/integration/manifests/ambassador.yaml
Labels: t:feature, size:S, lgtm

#5766 Add Mark Schlachter (@the-wondersmith) as a maintainer
  Community/MAINTAINERS.md
Labels: size:S, lgtm

#5757 Disable dependabot
  .github/dependabot-disabled.yml
Labels: size:XS, lgtm

#5780 dev/v4 sync
  .github/dependabot-disabled.yml
  Community/MAINTAINERS.md
Labels: size:S, lgtm
