Repository emissary-ingress/emissary, pull requests merged in 2025-08, with the labels that each got.

#5861 Update Go (first round)
  DEPENDENCIES.md
  build-aux/generate.mk
  build-aux/tools.mk
  go.mod
  go.sum
  manifests/emissary/emissary-crds.yaml.in
  pkg/api/getambassador.io/crds.yaml
  pkg/kates/client.go
  python/tests/src/tests/integration/manifests/crds.yaml
  test/apiext/testdata/crds.yaml
  tools/src/chart-doc-gen/go.mod
  tools/src/chart-doc-gen/pin.go
  tools/src/controller-gen/pin.go
  tools/src/conversion-gen/pin.go
  tools/src/crane/go.mod
  tools/src/crane/pin.go
  tools/src/ct/go.mod
  tools/src/ct/pin.go
  tools/src/go-mkopensource/pin.go
  tools/src/golangci-lint/go.mod
  tools/src/golangci-lint/go.sum
  tools/src/golangci-lint/pin.go
  tools/src/kubestatus/pin.go
  tools/src/ocibuild/go.mod
  tools/src/ocibuild/pin.go
  tools/src/protoc-gen-go-grpc/pin.go
  tools/src/protoc-gen-go/pin.go
  tools/src/py-list-deps.py
  tools/src/py-mkopensource/main.go
  tools/src/yq/go.mod
  tools/src/yq/pin.go
  unparsable-packages.yaml
Labels: dependencies, go, size:XL, lgtm

#5862 Cleaner UV setup
  .github/actions/setup-deps/action.yml
  DEPENDENCIES.md
  DEPENDENCY_LICENSES.md
  build-aux/builder.mk
  build-aux/deps.mk
  docker/emissary/Dockerfile
  pyproject.toml
  python/ambassador-diag/pyproject.toml
  python/ambassador-diag/src/ambassador_diag/diagd.py
  python/ambassador/pyproject.toml
  python/ambassador/src/ambassador/compile.py
  python/tests/src/tests/utils.py
Labels: dependencies, size:L, lgtm

#5864 Update CHANGELOG with correct metadata for 3.10 release
  CHANGELOG.md
  docs/releaseNotes.yml
Labels: size:XS, lgtm

#5865 chore: remove scout (ambassador labs telemetry)
  build-aux/builder.mk
  cmd/entrypoint/entrypoint.go
  pkg/metriton/install_id.go
  pkg/metriton/protocol.go
  pkg/metriton/reporter.go
  python/ambassador-diag/src/ambassador_diag/diagd.py
  python/ambassador/src/ambassador/__init__.py
  python/ambassador/src/ambassador/ambscout.py
  python/ambassador/src/ambassador/scout.py
  python/entrypoint.sh
  python/tests/src/tests/integration/test_scout.py
  releng/lib/check_artifacts.py
  tools/src/py-list-deps.py
Labels: python, go, size:XXL, lgtm

#5314 fix(helm): remove CPU limits
  charts/emissary-ingress/values.yaml.in
Labels: size:XS, lgtm

#5302 feat: set securityContext on emissary-apiext deployment
  manifests/emissary/emissary-crds.yaml.in
Labels: size:XS, lgtm

#5867 feat(service): provide options to pass `loadBalancerClass`
  charts/emissary-ingress/templates/service.yaml
  charts/emissary-ingress/values.yaml.in
Labels: t:feature, size:XS, lgtm
