Repository emissary-ingress/emissary, pull requests merged in 2025-03, with the labels that each got.

#5827 Update Python dependencies
  DEPENDENCIES.md
  build-aux/builder.mk
  build-aux/deps.mk
  python/requirements-dev.txt
  python/requirements.txt
  tools/src/py-mkopensource/main.go
Labels: dependencies, python, size:L, lgtm

#5795 [CI Run] ambex: Remove usage of md5
  CHANGELOG.md
  docs/releaseNotes.yml
  go.mod
  pkg/ambex/transforms.go
  pkg/ambex/transforms_test.go
Labels: t:bug, go, size:M, lgtm

#5831 Update the TRY-3.10 document for 3.10.0-rc.3.
  TRY-3.10.md
Labels: size:S, lgtm
